name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet.cli numpy

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Pre-build Clean
        run: flutter doctor # Vérifie que tout est OK pour Android

      - name: List files (Debug)
        run: ls -R # Ceci affichera tous tes fichiers dans les logs si ça plante

      - name: Build APK
        run: |
          flet build apk . --project "mon_ia"

          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
